export const USER_LOADED = 'USER_LOADED';

export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const COUNT_SERVER_CHARACTERS = 'COUNT_SERVER_CHARACTERS';
export const COUNT_SERVER_ASSISTANCES = 'COUNT_SERVER_ASSISTANCES';
export const COUNT_SERVER_REPORTS = 'COUNT_SERVER_REPORTS';
export const GROUP_BY_ASSISTANCES = 'GROUP_BY_ASSISTANCES';
export const GROUP_BY_REPORTS = 'GROUP_BY_REPORTS';
export const COUNT_SERVER_ERROR = 'COUNT_SERVER_ERROR';
export const CLEAR_STATS_ERROR = 'CLEAR_STATS_ERROR';

export const GET_ALL_QUIZ = 'GET_ALL_QUIZ';
export const ADD_QUIZ = 'ADD_QUIZ';
export const DELETE_QUIZ = 'DELETE_QUIZ';
export const SET_CURRENT_QUIZ = 'SET_CURRENT_QUIZ';
export const CLEAR_CURRENT_QUIZ = 'CLEAR_CURRENT_QUIZ';
export const UPDATE_QUIZ = 'UPDATE_QUIZ';
export const CLEAR_QUIZ = 'CLEAR_QUIZ';
export const QUIZ_ERROR = 'QUIZ_ERROR';
export const CLEAR_QUIZ_ERROR = 'CLEAR_QUIZ_ERROR';

export const GET_ALL_USER_APPS = 'GET_ALL_USER_APPS';
export const REQUEST_USER_APPS_APPROVAL = 'REQUEST_USER_APPS_APPROVAL';
export const UPDATE_USER_APPS = 'UPDATE_USER_APPS';
export const FILTER_USER_APPS = 'FILTER_USER_APPS';
export const CLEAR_FILTER_USER_APPS = 'CLEAR_FILTER_USER_APPS';
export const USER_APPS_ERROR = 'USER_APPS_ERROR';
export const CLEAR_USER_APPS_ERROR = 'CLEAR_USER_APPS_ERROR';

export const GET_ALL_BAN_LIST = 'GET_ALL_BAN_LIST';
export const DELETE_BAN = 'DELETE_BAN';
export const BAN_ERROR = 'BAN_ERROR';
export const CLEAR_BAN_ERROR = 'CLEAR_BAN_ERROR';

export const GET_ALL_NEWS = 'GET_ALL_NEWS';
export const ADD_NEWS = 'ADD_NEWS';
export const DELETE_NEWS = 'DELETE_NEWS';
export const SET_CURRENT_NEWS = 'SET_CURRENT_NEWS';
export const CLEAR_CURRENT_NEWS = 'CLEAR_CURRENT_NEWS';
export const UPDATE_NEWS = 'UPDATE_NEWS';
export const CLEAR_NEWS = 'CLEAR_NEWS';
export const NEWS_ERROR = 'NEWS_ERROR';
export const CLEAR_NEWS_ERROR = 'CLEAR_NEWS_ERROR';